# Generated by Django 3.1.3 on 2020-11-11 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.CharField(blank=True, default=None, max_length=55)),
                ('noOfQues', models.IntegerField(blank=True, default=None)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('timePerQues', models.CharField(blank=True, default=None, max_length=12)),
                ('Author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=None, max_length=200)),
                ('optionA', models.CharField(blank=True, default=None, max_length=50)),
                ('optionB', models.CharField(blank=True, default=None, max_length=50)),
                ('optionC', models.CharField(blank=True, default=None, max_length=50)),
                ('optionD', models.CharField(blank=True, default=None, max_length=50)),
                ('answer', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default=None, max_length=5)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Testmania.contests')),
                ('responseA', models.ManyToManyField(related_name='response_a', to=settings.AUTH_USER_MODEL)),
                ('responseB', models.ManyToManyField(related_name='response_b', to=settings.AUTH_USER_MODEL)),
                ('responseC', models.ManyToManyField(related_name='response_c', to=settings.AUTH_USER_MODEL)),
                ('responseD', models.ManyToManyField(related_name='response_d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
