# Generated by Django 3.1.3 on 2020-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default=None, max_length=5),
        ),
    ]
