# Generated by Django 3.1.3 on 2020-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(upload_to='staticfiles/images'),
        ),
    ]
