# Generated by Django 3.1.3 on 2020-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='participants',
        ),
        migrations.AddField(
            model_name='contests',
            name='contestName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionA',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionB',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionC',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='optionD',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
