# Generated by Django 3.1.3 on 2020-11-08 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='contest',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Testmania.contests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='optionC',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='optionD',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
