# Generated by Django 3.1.3 on 2020-11-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testmania', '0002_auto_20201108_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='contestName',
        ),
        migrations.AddField(
            model_name='contests',
            name='Author',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contests',
            name='contest',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='contests',
            name='endDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='contests',
            name='endTime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='contests',
            name='noOfQues',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='contests',
            name='startDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='contests',
            name='startTime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='contests',
            name='timePerQues',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='questions',
            name='responseA',
            field=models.ManyToManyField(related_name='response_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='responseB',
            field=models.ManyToManyField(related_name='response_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='responseC',
            field=models.ManyToManyField(related_name='response_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='responseD',
            field=models.ManyToManyField(related_name='response_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionA',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionB',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionC',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionD',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
