# Generated by Django 3.1.3 on 2020-11-12 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testmania', '0002_auto_20201111_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='participants',
            field=models.ManyToManyField(related_name='contest_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
