# Generated by Django 3.1.3 on 2020-11-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0002_auto_20201108_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='contest',
        ),
    ]
