# Generated by Django 3.1.3 on 2020-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0002_auto_20201124_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
