# Generated by Django 3.1.3 on 2020-11-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0003_remove_questions_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Testmania.contests'),
            preserve_default=False,
        ),
    ]
