# Generated by Django 3.1.3 on 2020-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0003_auto_20201124_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(default='default-user-icon.jpg', upload_to='images/user.username/'),
        ),
    ]
