# Generated by Django 3.1.3 on 2020-12-01 10:15

import Testmania.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0004_auto_20201201_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(default='default-user-icon.jpg', upload_to=Testmania.models.get_profile_path),
        ),
    ]
