# Generated by Django 3.1.3 on 2020-11-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0005_auto_20201108_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contests',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
