# Generated by Django 3.1.3 on 2020-12-02 07:22

import Testmania.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0005_auto_20201201_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(default='images/default-user-icon.jpg', upload_to=Testmania.models.get_profile_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Roll_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
