# Generated by Django 3.1.3 on 2020-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0006_auto_20201202_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='contest',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='contests',
            name='noOfQues',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contests',
            name='timePerQues',
            field=models.CharField(max_length=12),
        ),
    ]
