# Generated by Django 3.1.3 on 2020-11-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Testmania', '0006_auto_20201108_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=50)),
                ('optionB', models.CharField(max_length=50)),
                ('optionC', models.CharField(max_length=50)),
                ('optionD', models.CharField(max_length=50)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Testmania.contests')),
            ],
        ),
    ]
