# Generated by Django 3.1.3 on 2020-11-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testmania', '0007_contests_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='contest',
        ),
        migrations.DeleteModel(
            name='Contests',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
